[pytest]
asyncio_mode = auto
filterwarnings =
    error
    ignore::DeprecationWarning:jose.*
    ignore:.*datetime\.datetime\.utcnow.*:DeprecationWarning
    ignore:.*Using.*httpx.*with.*starlette\.testclient.*:DeprecationWarning
    ignore:.*httpx2.*:DeprecationWarning
    ignore::DeprecationWarning:starlette.*



