"""sih26229_update_languages_cash_ml_datasets

Revision ID: b55a21309efa
Revises: 
Create Date: 2026-09-19 14:49:45.304169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55a21309efa'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matching_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('trained_on_version', sa.String(length=36), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('demo_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synthetic_share', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('exported_anonymized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_quarantine',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_subcategories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.Column('name_mr', sa.String(length=100), nullable=False),
    sa.Column('name_pa', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('user_override', sa.Boolean(), nullable=False),
    sa.Column('final_value_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photo_id', sa.String(length=100), nullable=False),
    sa.Column('label_material_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('labeller_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['label_material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['labeller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycler_rates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recycler_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('sub_category_id', sa.String(length=36), nullable=True),
    sa.Column('rate_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['recyclers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aggregators') as batch_op:
        batch_op.add_column(sa.Column('service_area_geojson', sa.Text(), nullable=True))

    with op.batch_alter_table('faqs') as batch_op:
        batch_op.add_column(sa.Column('question_mr', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('answer_mr', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('lot_items') as batch_op:
        batch_op.add_column(sa.Column('sub_category_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=30), nullable=False, server_default='collector'))
        batch_op.create_foreign_key('fk_lot_items_sub_cat', 'material_subcategories', ['sub_category_id'], ['id'])

    with op.batch_alter_table('lot_photos') as batch_op:
        batch_op.add_column(sa.Column('phash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=True))

    with op.batch_alter_table('lots') as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False, server_default='real'))
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('materials') as batch_op:
        batch_op.add_column(sa.Column('name_mr', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('hazard_note_mr', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('safety_tip_mr', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False, server_default='real'))
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('notification_templates') as batch_op:
        batch_op.add_column(sa.Column('title_mr', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('body_mr', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('sms_mr', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('notifications') as batch_op:
        batch_op.add_column(sa.Column('title_mr', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('body_mr', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('payments') as batch_op:
        batch_op.add_column(sa.Column('gateway_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('upi_ref', existing_type=sa.VARCHAR(length=50), type_=sa.String(length=100), existing_nullable=True)

    with op.batch_alter_table('price_history') as batch_op:
        batch_op.add_column(sa.Column('sub_category_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=False, server_default='kg'))
        batch_op.add_column(sa.Column('buying_price_paise', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('quoted_price_paise', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('recycler_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('aggregator_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('recyclers') as batch_op:
        batch_op.add_column(sa.Column('service_area_geojson', sa.Text(), nullable=True))

    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False, server_default='cash'))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=30), nullable=False, server_default='settled'))
        batch_op.add_column(sa.Column('handover_ref', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('collection_lat', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('collection_lng', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('handover_lat', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('handover_lng', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('recycler_confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('recycler_confirmed_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('cash_confirmed_by_collector', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('collector_confirm_lat', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('collector_confirm_lng', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('cash_confirmed_by_buyer', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('buyer_confirm_lat', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('buyer_confirm_lng', sa.Numeric(precision=10, scale=6), nullable=True))
        batch_op.add_column(sa.Column('due_status', sa.String(length=20), nullable=False, server_default='cleared'))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False, server_default='real'))
        batch_op.add_column(sa.Column('is_synthetic', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.create_unique_constraint('uq_transactions_handover_ref', ['handover_ref'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('uq_transactions_handover_ref', type_='unique')
        batch_op.drop_column('is_synthetic')
        batch_op.drop_column('source')
        batch_op.drop_column('due_status')
        batch_op.drop_column('buyer_confirm_lng')
        batch_op.drop_column('buyer_confirm_lat')
        batch_op.drop_column('cash_confirmed_by_buyer')
        batch_op.drop_column('collector_confirm_lng')
        batch_op.drop_column('collector_confirm_lat')
        batch_op.drop_column('cash_confirmed_by_collector')
        batch_op.drop_column('recycler_confirmed_by')
        batch_op.drop_column('recycler_confirmed_at')
        batch_op.drop_column('handover_lng')
        batch_op.drop_column('handover_lat')
        batch_op.drop_column('collection_lng')
        batch_op.drop_column('collection_lat')
        batch_op.drop_column('handover_ref')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('recyclers') as batch_op:
        batch_op.drop_column('service_area_geojson')

    with op.batch_alter_table('price_history') as batch_op:
        batch_op.drop_column('is_synthetic')
        batch_op.drop_column('aggregator_id')
        batch_op.drop_column('recycler_id')
        batch_op.drop_column('quoted_price_paise')
        batch_op.drop_column('buying_price_paise')
        batch_op.drop_column('unit')
        batch_op.drop_column('sub_category_id')

    with op.batch_alter_table('payments') as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('bank_ref')
        batch_op.drop_column('gateway_ref')

    with op.batch_alter_table('notifications') as batch_op:
        batch_op.drop_column('body_mr')
        batch_op.drop_column('title_mr')

    with op.batch_alter_table('notification_templates') as batch_op:
        batch_op.drop_column('sms_mr')
        batch_op.drop_column('body_mr')
        batch_op.drop_column('title_mr')

    with op.batch_alter_table('materials') as batch_op:
        batch_op.drop_column('is_synthetic')
        batch_op.drop_column('source')
        batch_op.drop_column('safety_tip_mr')
        batch_op.drop_column('hazard_note_mr')
        batch_op.drop_column('name_mr')

    with op.batch_alter_table('lots') as batch_op:
        batch_op.drop_column('is_synthetic')
        batch_op.drop_column('source')

    with op.batch_alter_table('lot_photos') as batch_op:
        batch_op.drop_column('quality_score')
        batch_op.drop_column('phash')

    with op.batch_alter_table('lot_items') as batch_op:
        batch_op.drop_constraint('fk_lot_items_sub_cat', type_='foreignkey')
        batch_op.drop_column('source_type')
        batch_op.drop_column('sub_category_id')

    with op.batch_alter_table('faqs') as batch_op:
        batch_op.drop_column('answer_mr')
        batch_op.drop_column('question_mr')

    with op.batch_alter_table('aggregators') as batch_op:
        batch_op.drop_column('service_area_geojson')

    op.drop_table('anomaly_flags')
    op.drop_table('recycler_rates')
    op.drop_table('training_labels')
    op.drop_table('ml_predictions')
    op.drop_table('material_subcategories')
    op.drop_table('ingest_quarantine')
    op.drop_table('dataset_versions')
    op.drop_table('ml_models')
    op.drop_table('matching_weights')
    op.drop_table('datasets')
    # ### end Alembic commands ###
